# Generated by Django 3.2.9 on 2021-11-13 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APIppb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='password',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
